// Blog içerikleri ayrı dosyalarda tutulur - import sorunu olmaması için
// Her yazı için içerik bir fonksiyon olarak döndürülür

export function getContent(slug: string): string {
  const contents: Record<string, string> = {
    'fortigate-ha-ayarlari': getFortigateHA(),
    'zero-trust-mimarisi': getZeroTrust(),
    'sd-wan-wan-modernizasyonu': getSDWAN(),
    'hci-veri-merkezi-modernizasyonu': getHCI(),
    'azure-hybrid-cloud-stratejisi': getAzure(),
    'kvkk-uyumlu-veri-yedekleme': getKVKK(),
    'microsoft-365-lisans-optimizasyonu': getM365(),
    'cat6a-cat7-kablolama-rehberi': getCat6A(),
    'windows-server-2025-yenilikler': getWS2025(),
  }
  return contents[slug] || 'İçerik bulunamadı.'
}

function getFortigateHA(): string {
  return [
    '## FortiGate High Availability (HA) Nedir?',
    '',
    'FortiGate High Availability (HA), iki veya daha fazla FortiGate cihazının mantıksal olarak tek bir birim gibi çalışmasını sağlayan bir kümeleme teknolojisidir. Kurumsal ağlarda kesintisizliği garanti altına almak için kritik öneme sahiptir. FortiGate, bu amaçla kendi protokolü olan **FGCP (FortiGate Cluster Protocol)** kullanır.',
    '',
    'HA kurulu bir sistemde:',
    '- **Primary (Aktif) cihaz** tüm trafiği işler ve konfigürasyonu secondary ile senkronize eder',
    '- **Secondary (Pasif) cihaz** primary cihazın konfigürasyonunu anlık olarak alır',
    '- Arıza tespit edildiğinde **1-3 saniye** içinde otomatik failover gerçekleşir',
    '',
    '---',
    '',
    '## HA Modları: Active-Passive vs Active-Active',
    '',
    '### Active-Passive (A-P) Modu',
    '',
    'En yaygın kullanılan moddur. Sadece Primary cihaz aktif olarak trafik işler; Secondary cihaz bekleme modunda senkronize kalır.',
    '',
    '**Ne zaman tercih edilmeli?**',
    '- Trafik miktarı tek cihazın kapasitesinin altında olduğunda',
    '- Tutarlı ve öngörülebilir trafik akışı gerektiğinde',
    '- Troubleshoot kolaylığı öncelikli olduğunda',
    '',
    '### Active-Active (A-A) Modu',
    '',
    'Her iki cihaz da aynı anda trafik işler. Load balancing session bazlı yapılır.',
    '',
    '---',
    '',
    '## Gereksinimler ve Ön Hazırlık',
    '',
    'HA kümesi kurmadan önce şu gereksinimleri karşıladığınızdan emin olun:',
    '',
    '- Her iki FortiGate cihazı **aynı model ve donanım konfigürasyonunda** olmalıdır',
    '- **Aynı FortiOS versiyonu** yüklü olmalıdır',
    '- WAN ve LAN arayüzleri **statik IP** kullanmalıdır',
    '- Heartbeat linkleri için fiziksel kablo bağlantısı gereklidir',
    '',
    '---',
    '',
    '## Active-Passive HA Konfigürasyonu',
    '',
    '### Primary FortiGate',
    '',
    '```bash',
    'config system global',
    '    set hostname FG-Primary',
    'end',
    '',
    'config system ha',
    '    set mode a-p',
    '    set group-id 10',
    '    set group-name YITSER-HA-CLUSTER',
    '    set password HaCluster@2024',
    '    set hbdev port3 50 port4 50',
    '    set session-pickup enable',
    '    set override enable',
    '    set override-wait-time 60',
    '    set priority 200',
    '    set monitor port1 port2',
    'end',
    '```',
    '',
    '**Parametrelerin açıklaması:**',
    '- `mode a-p` — Active-Passive modunu etkinleştirir',
    '- `group-id 10` — Küme kimliği, her iki cihazda aynı olmalıdır (0-255)',
    '- `session-pickup enable` — TCP oturum tablosunun paylaşılmasını sağlar',
    '- `priority 200` — Primary cihaz önceliği (default 128, yüksek = tercihli)',
    '',
    '### Secondary FortiGate',
    '',
    '```bash',
    'config system ha',
    '    set mode a-p',
    '    set group-id 10',
    '    set group-name YITSER-HA-CLUSTER',
    '    set password HaCluster@2024',
    '    set hbdev port3 50 port4 50',
    '    set session-pickup enable',
    '    set override enable',
    '    set priority 100',
    '    set monitor port1 port2',
    'end',
    '```',
    '',
    '---',
    '',
    '## Active-Active HA Konfigürasyonu',
    '',
    '```bash',
    'config system ha',
    '    set mode a-a',
    '    set group-id 20',
    '    set group-name YITSER-AA-CLUSTER',
    '    set password HaCluster@2024',
    '    set hbdev port3 50 port4 50',
    '    set session-pickup enable',
    '    set load-balance-all enable',
    '    set override disable',
    '    set priority 200',
    'end',
    '```',
    '',
    '---',
    '',
    '## HA Durumunu Kontrol Etme',
    '',
    '```bash',
    'get sys ha status',
    '',
    '# Beklenen çıktı:',
    '# HA Health Status: OK',
    '# Mode: HA Active Passive',
    '# Group: YITSER-HA-CLUSTER',
    '',
    '# Detaylı diagnostics',
    'diagnose sys ha status',
    'diagnose sys ha checksum cluster',
    '```',
    '',
    '---',
    '',
    '## Management Interface Rezervasyonu',
    '',
    'Her iki cihaza ayrı ayrı erişebilmek için:',
    '',
    '```bash',
    'config system ha',
    '    set ha-mgmt-status enable',
    '    config ha-mgmt-interfaces',
    '        edit 1',
    '            set interface mgmt',
    '            set gateway 192.168.1.1',
    '        next',
    '    end',
    'end',
    '```',
    '',
    '---',
    '',
    '## Yaygın Sorunlar ve Çözümleri',
    '',
    '### Sorun 1: Cihazlar senkronize olmuyor',
    '',
    '```bash',
    'diagnose sys ha checksum show',
    'diagnose sys ha checksum cluster',
    '```',
    '',
    '### Sorun 2: Heartbeat bağlantı hatası',
    '',
    '```bash',
    'diagnose netlink interface list',
    'get hardware nic port3',
    '```',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'FortiGate HA konfigürasyonu, kurumsal ağlarda kesintisizliği sağlamanın en güvenilir yollarından biridir. Active-Passive mod daha öngörülebilir ve sorun giderimi kolay bir mimari sunarken, Active-Active mod yüksek trafik hacimlerinde performans avantajı sağlar. **Yitser Teknoloji** olarak her iki mod için de tasarım, kurulum ve yönetilen destek hizmetleri sunuyoruz.',
  ].join('\n')
}

function getZeroTrust(): string {
  return [
    '## Zero Trust Nedir?',
    '',
    '"Never Trust, Always Verify" — Hiçbir zaman güvenme, her zaman doğrula. Bu prensip, 2010 yılında Forrester Research tarafından ortaya atılan ve günümüzde kurumsal siber güvenliğin temel taşı haline gelen **Zero Trust** mimarisinin özüdür.',
    '',
    'Geleneksel perimeter güvenlik anlayışı, ağın içindeki her şeyin güvenilir olduğunu varsayar. Zero Trust bu varsayımı tamamen ortadan kaldırır: **Ağın içinde olman seni güvenilir yapmaz.**',
    '',
    "Zero Trust'ın üç temel prensibi:",
    '- **Açık doğrulama:** Her erişim talebinde kimlik, cihaz sağlığı ve bağlam doğrulanır',
    '- **En az ayrıcalık:** Kullanıcılar yalnızca ihtiyaç duydukları kaynaklara erişebilir',
    '- **İhlal varsayımı:** Sisteme sızılmış gibi davranılır; lateral movement minimize edilir',
    '',
    '---',
    '',
    '## Neden Zero Trust?',
    '',
    'IBM 2024 Cost of Data Breach raporuna göre, veri ihlallerinin **%67\'si** yetersiz kimlik doğrulama ve erişim kontrol mekanizmalarından kaynaklanmaktadır.',
    '',
    '- Bulut ve hibrit çalışma modellerinde perimeter kavramı ortadan kalkmaktadır',
    '- Ransomware ve lateral movement saldırıları her sektörde artmaktadır',
    '- KVKK ve ISO 27001 uyumluluk gereksinimleri sıkılaşmaktadır',
    '',
    '---',
    '',
    '## 1. Kimlik ve Erişim Yönetimi (IAM/PAM)',
    '',
    "Zero Trust'ın kalbi kimlik doğrulamadır. Her kullanıcı, her cihaz ve her uygulama için güçlü kimlik doğrulama zorunludur.",
    '',
    '### Çok Faktörlü Kimlik Doğrulama (MFA)',
    '',
    '- **TOTP:** Google Authenticator, Microsoft Authenticator',
    '- **FIDO2/WebAuthn:** Phishing-resistant hardware keys (YubiKey)',
    '- **Push notifications:** Duo Security, Okta Verify',
    '',
    '### Conditional Access (Azure AD / Entra ID)',
    '',
    '```',
    'Politika: Kurumsal Uygulamalar Erişimi',
    'Koşullar:',
    '  Kullanıcı: Tüm kullanıcılar',
    '  Uygulama: SharePoint, Teams, ERP',
    '  Cihaz: Sadece Intune kayıtlı ve compliant cihazlar',
    '  Risk skoru: Düşük veya orta',
    'Kontroller:',
    '  MFA zorunlu',
    '  Compliant cihaz zorunlu',
    '  Oturum süresi: 8 saat',
    '```',
    '',
    '---',
    '',
    '## 2. Mikro Segmentasyon',
    '',
    'Geleneksel VLAN tabanlı segmentasyon yetersiz kalmaktadır. Mikro segmentasyon, iş yükü ve uygulama seviyesinde granüler segmentasyon sağlar.',
    '',
    '```bash',
    '# NSX-T Distributed Firewall kuralı',
    'Rule: DB-to-App-Only',
    '  Source: Web-Tier-SG',
    '  Destination: App-Tier-SG',
    '  Service: TCP/8080, TCP/8443',
    '  Action: ALLOW',
    '',
    'Rule: Block-All-Other-East-West',
    '  Source: Any',
    '  Destination: Any',
    '  Service: Any',
    '  Action: BLOCK',
    '  Log: ENABLED',
    '```',
    '',
    '---',
    '',
    '## 3. ZTNA — Zero Trust Network Access',
    '',
    "ZTNA, geleneksel VPN'in yerine geçen modern uzak erişim modelidir.",
    '',
    '| Özellik | VPN | ZTNA |',
    '|---------|-----|------|',
    '| Erişim granülaritesi | Tüm ağ | Uygulama bazlı |',
    '| Kimlik doğrulama | Bağlantıda bir kez | Her oturumda sürekli |',
    '| Lateral movement riski | Yüksek | Çok düşük |',
    '',
    '### FortiGate ZTNA Konfigürasyonu',
    '',
    '```bash',
    'config ztna server',
    '    edit "internal-app-server"',
    '        set type tcp-forwarding',
    '        set server 192.168.10.50',
    '        set service 443',
    '    next',
    'end',
    '',
    'config firewall policy',
    '    edit 100',
    '        set name "ZTNA-App-Access"',
    '        set ztna-status enable',
    '        set ztna-ems-tag "compliant-device"',
    '        set logtraffic all',
    '    next',
    'end',
    '```',
    '',
    '---',
    '',
    '## Zero Trust Yol Haritası',
    '',
    '**Faz 1 (0-3 Ay):** MFA tüm kritik uygulamalara, PAM ile ayrıcalıklı hesaplar korunur',
    '',
    '**Faz 2 (3-6 Ay):** EDR/XDR dağıtımı, cihaz uyumluluk kontrolü, SIEM kurulumu',
    '',
    '**Faz 3 (6-12 Ay):** VPN\'den ZTNA\'ya geçiş, uygulama bazlı erişim politikaları',
    '',
    '**Faz 4 (12+ Ay):** SOC ve tehdit avı programı, otomatik yanıt (SOAR)',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'Zero Trust mimarisi, modern siber tehditlere karşı en etkili savunma yaklaşımıdır. **Yitser Teknoloji** olarak Zero Trust değerlendirmesi, tasarımı ve uygulama hizmetleri sunuyoruz.',
  ].join('\n')
}

function getSDWAN(): string {
  return [
    '## SD-WAN Nedir?',
    '',
    'Software-Defined Wide Area Network (SD-WAN), geniş alan ağlarını yazılım tabanlı bir orkestrasyon katmanıyla yöneten modern bir ağ teknolojisidir. Yüksek maliyetli MPLS bağlantıları yerine internet bağlantılarını akıllıca kullanan SD-WAN, kurumsal WAN altyapısını köklü biçimde dönüştürmektedir.',
    '',
    '**Geleneksel WAN\'ın sorunları:**',
    '- MPLS devreleri broadband\'e kıyasla %300-500 daha pahalıdır',
    '- Yeni lokasyon bağlantısı 30-90 gün sürebilir',
    '- Uygulama bazlı trafik kontrolü mümkün değildir',
    '- Bulut uygulamaları (Microsoft 365, Salesforce) için backhauling problemi',
    '',
    '---',
    '',
    '## FortiGate SD-WAN Konfigürasyonu',
    '',
    '### Adım 1: SD-WAN Zone Oluşturma',
    '',
    '```bash',
    'config system sdwan',
    '    set status enable',
    '    config zone',
    '        edit "virtual-wan-link"',
    '        next',
    '    end',
    '    config members',
    '        edit 1',
    '            set interface "wan1"',
    '            set gateway 203.0.113.1',
    '            set priority 10',
    '            set status enable',
    '        next',
    '        edit 2',
    '            set interface "wan2"',
    '            set gateway 198.51.100.1',
    '            set priority 20',
    '            set status enable',
    '        next',
    '    end',
    'end',
    '```',
    '',
    '### Adım 2: Performance SLA Tanımları',
    '',
    '```bash',
    'config system sdwan',
    '    config health-check',
    '        edit "Microsoft-365-SLA"',
    '            set server "13.107.6.152"',
    '            set protocol https',
    '            set interval 500',
    '            set failure-count 3',
    '            set threshold-latency 150',
    '            set threshold-jitter 30',
    '            set threshold-packetloss 2',
    '            set members 1 2',
    '        next',
    '        edit "General-Internet-SLA"',
    '            set server "8.8.8.8"',
    '            set protocol ping',
    '            set interval 1000',
    '            set threshold-latency 200',
    '            set threshold-packetloss 5',
    '            set members 1 2',
    '        next',
    '    end',
    'end',
    '```',
    '',
    '### Adım 3: SD-WAN Yönlendirme Kuralları',
    '',
    '```bash',
    'config system sdwan',
    '    config service',
    '        edit 1',
    '            set name "VoIP-Priority"',
    '            set mode priority',
    '            set protocol 17',
    '            set link-cost-factor latency',
    '            set health-check "General-Internet-SLA"',
    '        next',
    '        edit 2',
    '            set name "Microsoft-365-Route"',
    '            set mode sla',
    '            set dst "13.107.0.0/16" "52.96.0.0/14"',
    '            set health-check "Microsoft-365-SLA"',
    '        next',
    '        edit 3',
    '            set name "General-Traffic"',
    '            set mode load-balance',
    '            set members 1 2',
    '        next',
    '    end',
    'end',
    '```',
    '',
    '---',
    '',
    '## MPLS ile SD-WAN Maliyet Karşılaştırması',
    '',
    '20 lokasyonlu bir kurum için yıllık maliyet analizi:',
    '',
    '| Model | Aylık/Lokasyon | Yıllık Toplam |',
    '|-------|----------------|---------------|',
    '| MPLS | 8.000 TL | 1.920.000 TL |',
    '| SD-WAN | 2.000 TL | 480.000 TL |',
    '| **Tasarruf** | **6.000 TL** | **1.440.000 TL (%75)** |',
    '',
    '---',
    '',
    '## MPLS\'ten SD-WAN\'a Geçiş Stratejisi',
    '',
    '**Faz 1 (1-2 Ay):** SD-WAN cihazları MPLS\'in yanına konumlandırılır. Internet trafiği SD-WAN ile yönlendirilir.',
    '',
    '**Faz 2 (2-4 Ay):** Kritik uygulamalar MPLS SLA ile izlenir, SD-WAN üzerinden paralel test yapılır.',
    '',
    '**Faz 3 (4-6 Ay):** MPLS devresi devre dışı bırakılır. Tam SD-WAN operasyonuna geçilir.',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'SD-WAN, kurumsal WAN altyapısını hem maliyet hem de performans açısından köklü biçimde iyileştiren bir teknolojik dönüşümdür. **Yitser Teknoloji** olarak marka bağımsız yaklaşımımızla FortiGate, Cisco ve Aruba SD-WAN platformlarında tasarım, geçiş ve yönetilen hizmet sunuyoruz.',
  ].join('\n')
}

function getHCI(): string {
  return [
    '## Hiperkonverjans Altyapısı (HCI) Nedir?',
    '',
    'Hyper-Converged Infrastructure (HCI), compute, storage, networking ve virtualization bileşenlerini tek bir yazılım tanımlı platform üzerinde birleştiren modern veri merkezi mimarisidir.',
    '',
    '| Kriter | 3-Tier Mimari | HCI |',
    '|--------|--------------|-----|',
    '| Başlangıç maliyeti | Yüksek | Orta |',
    '| Ölçekleme | Katman bazlı, karmaşık | Node ekleyerek linear |',
    '| Yönetim | 3 ayrı ekip/araç | Tek konsol |',
    '| Kurulum süresi | Haftalar | Saatler |',
    '',
    '---',
    '',
    '## VMware vSAN Konfigürasyonu',
    '',
    '### vSAN Disk Grubu Oluşturma (PowerCLI)',
    '',
    '```powershell',
    '# vCenter\'a bağlan',
    'Connect-VIServer -Server vcenter.yitser.local -User administrator@vsphere.local',
    '',
    '# vSAN cluster etkinleştir',
    '$cluster = Get-Cluster "Production-Cluster"',
    'Set-Cluster -Cluster $cluster -VsanEnabled $true',
    '',
    '# Disk gruplarını yapılandır',
    '$hosts = Get-VMHost -Location $cluster',
    'foreach ($vmhost in $hosts) {',
    '    $cacheDisk = Get-VMHostDisk -VMHost $vmhost |',
    '        Where-Object {$_.Vendor -like "*INTEL*"} | Select-Object -First 1',
    '    $capacityDisks = Get-VMHostDisk -VMHost $vmhost |',
    '        Where-Object {$_.RotationRate -ne 0}',
    '    New-VsanDiskGroup -VMHost $vmhost -CacheDisk $cacheDisk -DataDisk $capacityDisks',
    '}',
    '```',
    '',
    '### vSAN Storage Policy',
    '',
    '```powershell',
    '# FTT=1 - RAID-1 politikası (1 host arızasına dayanıklı)',
    '# Minimum 3 node gerektirir',
    '',
    '# FTT=2 - RAID-6 politikası (2 host arızasına dayanıklı)',
    '# Minimum 6 node gerektirir',
    '',
    '# vSAN health kontrol',
    'Get-VsanClusterConfiguration -Cluster $cluster',
    '```',
    '',
    '---',
    '',
    '## Nutanix AOS Konfigürasyonu',
    '',
    '```bash',
    '# Cluster bilgisi',
    'ncli cluster info',
    '',
    '# Cluster adı ayarla',
    'ncli cluster edit-params new-name="YITSER-PROD-CLUSTER"',
    '',
    '# DNS ve NTP',
    'ncli cluster add-to-name-servers servers="192.168.1.10,192.168.1.11"',
    'ncli cluster edit-params ntp-servers="192.168.1.12"',
    '',
    '# Container oluştur (RF=2, sıkıştırma + deduplicate)',
    'ncli container create name="Production-VMs" sp-name="SP-SSD-TIER" rf=2 compression-enabled=true dedupe-enabled=true',
    '',
    '# Kritik iş yükleri için RF=3',
    'ncli container create name="Critical-DBs" sp-name="SP-SSD-TIER" rf=3 compression-enabled=true',
    '```',
    '',
    '---',
    '',
    '## HCI Kapasite Planlaması',
    '',
    '```',
    'Örnek: 100 vCPU, 512 GB RAM ihtiyacı',
    '',
    'HA overhead ile (N+1): %25 ekle',
    'Önerilen 4 node konfigürasyonu:',
    '  CPU: 2x Intel Xeon Silver 4310 (24 core/node)',
    '  RAM: 256 GB DDR4 ECC/node',
    '  Cache: 2x 3.84 TB NVMe SSD/node',
    '  Capacity: 6x 12 TB SAS HDD/node',
    '',
    'Toplam: 96 fiziksel core, 1 TB RAM, 288 TB ham depolama',
    '```',
    '',
    '---',
    '',
    '## Yaygın Sorunlar',
    '',
    '### vSAN Network Sorunları',
    '',
    '```bash',
    '# vSAN ağ ping testi',
    'esxcli vsan debug vmknic ping -H 192.168.200.10 -I vmk1',
    '',
    '# Network konfigürasyon kontrolü',
    'esxcli vsan network list',
    '',
    '# MTU kontrolü (9000 Jumbo Frame önerilir)',
    'esxcli network nic get -n vmnic0 | grep MTU',
    '```',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'HCI, özellikle yeni veri merkezi kurulumlarında en hızlı ROI sağlayan yaklaşımlardan biridir. **Yitser Teknoloji** olarak VMware vSAN, Nutanix ve Dell VxRail platformlarında tam kapsamlı HCI tasarım, kurulum ve destek hizmetleri sunuyoruz.',
  ].join('\n')
}

function getAzure(): string {
  return [
    '## Azure Hibrit Bulut Nedir?',
    '',
    'Hibrit bulut, on-premise (şirket içi) altyapı ile public cloud hizmetlerini bir arada kullanan ve bunlar arasında kesintisiz entegrasyon sağlayan mimaridir. Microsoft Azure, hibrit bulut senaryoları için son derece kapsamlı araçlar sunmaktadır.',
    '',
    '**Hibrit bulut stratejisinin avantajları:**',
    '- Veri egemenliği gerektiren iş yükleri on-premise\'de kalır',
    '- Esnek iş yükleri (test, dev) buluta taşınır',
    '- KVKK uyumluluğu korunur',
    '- Mevcut yatırımlar korunur',
    '',
    '---',
    '',
    '## Azure ExpressRoute',
    '',
    'ExpressRoute, şirket ağınız ile Azure arasında özel, şifreli bağlantı sağlar.',
    '',
    '**Avantajları:**',
    '- Tutarlı düşük gecikme (tipik olarak <10ms Türkiye\'den)',
    '- Bant genişliği garantisi (50 Mbps - 100 Gbps)',
    '- SLA garantisi (%99.95 uptime)',
    '',
    '```powershell',
    '# ExpressRoute Circuit oluştur',
    'New-AzResourceGroup -Name "YITSER-Network-RG" -Location "West Europe"',
    '',
    '$circuit = New-AzExpressRouteCircuit `',
    '  -Name "YITSER-ExpressRoute" `',
    '  -ResourceGroupName "YITSER-Network-RG" `',
    '  -Location "West Europe" `',
    '  -SkuTier Standard `',
    '  -SkuFamily MeteredData `',
    '  -ServiceProviderName "Turkcell" `',
    '  -PeeringLocation "Istanbul" `',
    '  -BandwidthInMbps 1000',
    '',
    '# Service Key (provider\'a iletilir)',
    '$circuit.ServiceKey',
    '```',
    '',
    '---',
    '',
    '## Azure AD Connect (Hibrit Kimlik)',
    '',
    'Azure AD Connect, on-premise Active Directory\'yi Azure AD ile senkronize eder.',
    '',
    '```powershell',
    '# Senkronizasyon başlat',
    'Start-ADSyncSyncCycle -PolicyType Delta',
    '',
    '# Tam senkronizasyon',
    'Start-ADSyncSyncCycle -PolicyType Initial',
    '',
    '# Senkronizasyon durumu',
    'Get-ADSyncConnectorRunStatus',
    '```',
    '',
    '---',
    '',
    '## Azure Arc ile On-Premise Yönetimi',
    '',
    '```bash',
    '# Windows Server - Arc Agent kurulum',
    'Invoke-WebRequest -Uri https://aka.ms/AzureConnectedMachineAgent -OutFile AzureConnectedMachineAgent.msi',
    'Start-Process msiexec.exe -ArgumentList "/i AzureConnectedMachineAgent.msi /qn" -Wait',
    '',
    '# Sunucuyu Azure Arc\'a bağla',
    'azcmagent connect --resource-group "YITSER-ARC-RG" --location "westeurope"',
    '```',
    '',
    '```bash',
    '# Linux - Arc Agent kurulum',
    'wget https://aka.ms/azcmagent -O install_linux_azcmagent.sh',
    'sudo bash install_linux_azcmagent.sh',
    'sudo azcmagent connect --resource-group "YITSER-ARC-RG" --location "westeurope"',
    '```',
    '',
    '---',
    '',
    '## Azure Migrate ile Assessment',
    '',
    '```powershell',
    '# Azure Migrate projesi oluştur',
    'New-AzMigrateProject `',
    '  -ResourceGroupName "YITSER-Migrate-RG" `',
    '  -Name "YITSER-Migration-Project" `',
    '  -Location "westeurope"',
    '```',
    '',
    '---',
    '',
    '## 6R Migration Framework',
    '',
    '| Strateji | Açıklama | Ne Zaman? |',
    '|----------|----------|-----------|',
    '| Rehost (Lift & Shift) | VM\'i olduğu gibi taşı | Hızlı geçiş |',
    '| Replatform | Küçük optimizasyonla taşı | Managed DB geçişi |',
    '| Repurchase | SaaS\'a geç | Exchange → M365 |',
    '| Refactor | Yeniden mimariye çevir | Cloud-native dönüşüm |',
    '| Retire | Devre dışı bırak | Kullanılmayan sistemler |',
    '| Retain | On-premise\'de bırak | Compliance gereksinimleri |',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'Azure hibrit bulut stratejisi, on-premise yatırımlarınızı korurken bulutun esnekliğinden yararlanmanızı sağlar. **Yitser Teknoloji** olarak Azure migrasyonu ve hibrit bulut danışmanlığı konularında marka bağımsız hizmet sunuyoruz.',
  ].join('\n')
}

function getKVKK(): string {
  return [
    '## KVKK ve Veri Yedekleme',
    '',
    'Kişisel Verilerin Korunması Kanunu (KVKK / 6698 sayılı Kanun), veri yedekleme sistemleri için kritik yükümlülükler getirmektedir. Yedekler genellikle büyük miktarda kişisel veri içerdiğinden, KVKK kapsamında özel önem taşır.',
    '',
    'KVKK madde 12 gereği veri sorumluları, kişisel verilerin korunması için uygun teknik ve idari tedbirleri almak zorundadır.',
    '',
    '---',
    '',
    '## 3-2-1-1-0 Backup Standardı',
    '',
    '- **3:** En az 3 kopya yedek tutun',
    '- **2:** En az 2 farklı medya tipinde saklayın (disk + tape/cloud)',
    '- **1:** En az 1 kopya tesis dışında (offsite)',
    '- **1:** En az 1 kopya offline veya immutable (değiştirilemez)',
    '- **0:** Tüm yedekler hatasız ve doğrulanmış olsun',
    '',
    '```',
    'Kopya 1: Local disk backup (Veeam Repository - NAS/SAN)',
    '         Retention: Son 14 gün (günlük)',
    '',
    'Kopya 2: Local tape backup (LTO-9)',
    '         Retention: Son 4 hafta (haftalık)',
    '         Offline kasada güvenli saklama',
    '',
    'Kopya 3: Azure Blob Storage (RA-GRS)',
    '         Immutable storage - 90 gün değiştirilemez',
    '         Retention: 1 yıl aylık, 7 yıl yıllık',
    '```',
    '',
    '---',
    '',
    '## Şifreleme ile KVKK Uyumu',
    '',
    '```powershell',
    '# Veeam ile AES-256 şifreleme',
    'Add-VBREncryptionKey -Password "BackupKey@Yitser2024" -Description "KVKK-Compliant-Key"',
    '',
    '$job = Get-VBRJob -Name "Production-VMs-Backup"',
    '$encKey = Get-VBREncryptionKey | Where-Object {$_.Description -eq "KVKK-Compliant-Key"}',
    '',
    'Set-VBRJobAdvancedStorageOptions -Job $job -EnableEncryption $true -EncryptionKey $encKey',
    '```',
    '',
    '```bash',
    '# Linux - GPG ile backup şifreleme',
    'tar -czf - /backup/database/ | gpg --recipient backup@yitser.com --encrypt -o /backup/encrypted/db_$(date +%Y%m%d).gpg',
    '',
    '# Şifreli backup doğrulama',
    'gpg --decrypt /backup/encrypted/db_20241201.gpg | tar -tzf -',
    '```',
    '',
    '---',
    '',
    '## Immutable Backup Konfigürasyonu',
    '',
    '```powershell',
    '# Azure Blob Immutable Storage',
    '$ctx = New-AzStorageContext -StorageAccountName "yitserbkp" -UseConnectedAccount',
    '',
    '# 90 günlük immutable retention',
    'Set-AzStorageObjectImmutabilityPolicy `',
    '  -Container "kvkk-backups" `',
    '  -Context $ctx `',
    '  -ExpiresOn (Get-Date).AddDays(90) `',
    '  -PolicyMode Unlocked',
    '```',
    '',
    '```bash',
    '# Linux Hardened Repository - Immutable flag',
    'sudo chattr +i /mnt/veeam-backup/backup_job_20241201.vbk',
    '',
    '# Flag kontrolü',
    'lsattr /mnt/veeam-backup/backup_job_20241201.vbk',
    '# Çıktı: ----i---------e---- backup_job_20241201.vbk',
    '```',
    '',
    '---',
    '',
    '## KVKK Saklama Süreleri',
    '',
    '| Veri Türü | Yasal Dayanak | Önerilen Saklama |',
    '|-----------|---------------|-----------------|',
    '| HR verileri | İş Kanunu | 10 yıl |',
    '| Muhasebe | VUK 253. Madde | 10 yıl |',
    '| Müşteri işlem | Borçlar Kanunu | 5 yıl |',
    '| Log kayıtları | 5651 sayılı Kanun | 2 yıl |',
    '| Kamera görüntüsü | KVKK | 30-90 gün |',
    '',
    '---',
    '',
    '## Güvenli Veri İmhası',
    '',
    '```bash',
    '# Disk overwriting - DoD 5220.22-M (3-pass)',
    'sudo shred -vzn 3 /dev/sdb',
    '',
    '# SSD için secure erase (ATA komutu)',
    'sudo hdparm --security-erase-enhanced PASSWORD /dev/sdb',
    '```',
    '',
    '---',
    '',
    '## Otomatik Backup Doğrulama (SureBackup)',
    '',
    '```powershell',
    '# Veeam SureBackup - haftalık otomatik restore testi',
    '$appGroup = Add-VBRApplicationGroup -Name "KVKK-Critical-VMs"',
    '$vLab = Add-VBRVirtualLab -Name "Restore-Test-Lab"',
    '',
    'Add-VBRSureBackupJob `',
    '  -Name "Weekly-Restore-Test" `',
    '  -ApplicationGroup $appGroup `',
    '  -VirtualLab $vLab `',
    '  -Schedule (New-VBRScheduleOptions -Weekly -Days Sunday -At "02:00")',
    '```',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'KVKK uyumlu veri yedekleme, hem hukuki zorunluluk hem de iş sürekliliğinin güvencesidir. **Yitser Teknoloji** olarak KVKK teknik tedbirler danışmanlığı, backup sistem tasarımı ve uyumluluk denetim hazırlığı konularında kapsamlı hizmet sunuyoruz.',
  ].join('\n')
}

function getM365(): string {
  return [
    '## Microsoft 365 Lisans Karmaşıklığı',
    '',
    'Microsoft 365, kurumsal kullanıcılara yüzlerce farklı lisans seçeneği sunmaktadır. Araştırmalar, kurumların Microsoft 365 harcamalarının **%25-40\'ının** optimize edilebilir nitelikte olduğunu göstermektedir.',
    '',
    '---',
    '',
    '## Microsoft 365 Plan Karşılaştırması',
    '',
    '| Plan | Özellik | Aylık/Kullanıcı |',
    '|------|---------|-----------------|',
    '| M365 F1 | Web/mobil, Teams, 2GB Exchange | ~150 TL |',
    '| M365 F3 | F1 + masaüstü uygulamalar | ~300 TL |',
    '| M365 E1 | Web/mobil + Exchange + Teams | ~400 TL |',
    '| M365 E3 | E1 + masaüstü + gelişmiş uyumluluk | ~800 TL |',
    '| M365 E5 | E3 + Defender P2 + Power BI Pro | ~1.400 TL |',
    '',
    '---',
    '',
    '## Kullanılmayan Lisansları Tespit Etme',
    '',
    '```powershell',
    '# Microsoft Graph ile bağlan',
    'Connect-MgGraph -Scopes "Reports.Read.All", "User.Read.All"',
    '',
    '# Son 90 günde aktif olmayan kullanıcılar',
    '$inactive = Get-MgReportOffice365ActiveUserDetail -Period D90 |',
    '  ConvertFrom-Csv |',
    '  Where-Object { $_."Is Active" -eq "False" } |',
    '  Select-Object "User Principal Name", "Last Activity Date", "Assigned Products"',
    '',
    '$inactive | Export-Csv "inactive-users.csv" -NoTypeInformation',
    'Write-Host "Aktif olmayan kullanici: $($inactive.Count)"',
    '```',
    '',
    '```powershell',
    '# Lisans atama vs kullanım analizi',
    'Get-MgSubscribedSku | Select-Object SkuPartNumber,',
    '  @{N="Total";E={$_.PrepaidUnits.Enabled}},',
    '  @{N="Assigned";E={$_.ConsumedUnits}},',
    '  @{N="Available";E={$_.PrepaidUnits.Enabled - $_.ConsumedUnits}} |',
    '  Sort-Object Available -Descending | Format-Table -AutoSize',
    '```',
    '',
    '---',
    '',
    '## Kullanıcı Segmentasyonu ile Optimizasyon',
    '',
    '| Segment | Profil | Önerilen Lisans |',
    '|---------|--------|-----------------|',
    '| Bilgi çalışanı | Ofis, e-posta, Teams | M365 E3 |',
    '| Yönetici/Analist | E3 + güvenlik | M365 E5 |',
    '| Saha çalışanı | Sadece mobil | M365 F1/F3 |',
    '| Servis hesabı | Sadece e-posta kutusu | Exchange Online P1 |',
    '| Toplantı odası | Teams Rooms | Teams Rooms Basic |',
    '',
    '---',
    '',
    '## Add-on ile Maliyet Tasarrufu',
    '',
    '```',
    'Senaryo: 200 kullanici, 20 tanesi gelismis guvenlik gerektirir',
    '',
    'Yanlis: 200 x M365 E5 = 200 x 1.300 TL = 260.000 TL/ay',
    '',
    'Dogru:',
    '  180 x M365 E3 = 180 x 750 TL = 135.000 TL/ay',
    '  20 x E3 + Defender P2 = 20 x 1.100 TL = 22.000 TL/ay',
    '  Toplam: 157.000 TL/ay',
    '',
    'Tasarruf: 103.000 TL/ay = 1.236.000 TL/yil (%40)',
    '```',
    '',
    '---',
    '',
    '## Otomatik Lisans Geri Kazanımı',
    '',
    '```powershell',
    '# 90+ gun login olmayan kullanicilarin lisanslarini kaldir',
    '$cutoff = (Get-Date).AddDays(-90)',
    '',
    'Get-MgUser -All -Property "DisplayName,UserPrincipalName,SignInActivity,AssignedLicenses" |',
    '  Where-Object { $_.SignInActivity.LastSignInDateTime -lt $cutoff -and $_.AssignedLicenses.Count -gt 0 } |',
    '  ForEach-Object {',
    '    Write-Host "Lisans kaldirilacak: $($_.DisplayName)"',
    '    Set-MgUserLicense -UserId $_.Id -AddLicenses @() -RemoveLicenses $_.AssignedLicenses.SkuId',
    '  }',
    '```',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'Microsoft 365 lisans yönetimi, doğru yapıldığında kurumsal BT bütçesinin %25-40\'ını geri kazandırabilecek stratejik bir alandır. **Yitser Teknoloji** olarak Microsoft lisans denetimi, optimizasyon ve CSP üzerinden lisans satışı konularında kapsamlı hizmet sunuyoruz.',
  ].join('\n')
}

function getCat6A(): string {
  return [
    '## Yapısal Kablolama Kategorileri',
    '',
    '| Kategori | Maks. Hız | Bant Genişliği | Maks. Mesafe | Standart |',
    '|----------|-----------|----------------|--------------|---------|',
    '| Cat5e | 1 Gbps | 100 MHz | 100 m | TIA-568-B.2 |',
    '| Cat6 | 1/10 Gbps | 250 MHz | 100/55 m | TIA-568-B.2-1 |',
    '| Cat6A | 10 Gbps | 500 MHz | 100 m | TIA-568-C.2 |',
    '| Cat7 | 10 Gbps | 600 MHz | 100 m | ISO/IEC 11801 |',
    '| Cat7A | 40 Gbps | 1000 MHz | 100 m | ISO/IEC 11801 |',
    '| Cat8 | 25/40 Gbps | 2000 MHz | 30 m | TIA-568-C.2-1 |',
    '',
    '---',
    '',
    '## Cat6A mı, Cat7 mi?',
    '',
    '### Cat6A (Augmented Category 6)',
    '',
    'Cat6A, 10 Gigabit Ethernet\'i 100 metre boyunca destekler ve TIA/EIA-568 standardı kapsamında tanımlanmıştır.',
    '',
    '**Cat6A avantajları:**',
    '- TIA-568 ve ISO/IEC 11801 her ikisini de destekler',
    '- Standart RJ45 konnektör kullanır (ekipman uyumluluğu mükemmel)',
    '- Patchpanel ve modüller yaygın ve ekonomik',
    '',
    '### Cat7 (Class F)',
    '',
    'Cat7, ISO/IEC 11801 standardı kapsamında tanımlanmıştır. Her çift ve kablonun tamamı topraklı ekranlıdır (S/FTP veya PiMF).',
    '',
    '**Cat7 dezavantajları:**',
    '- GG45 veya TERA konnektör gerektirir (standart RJ45 ile Cat7 tam performans vermez)',
    '- Daha pahalı konnektör ve patchpanel',
    '- RJ45 ile kullanılırsa Cat6A performansına düşer',
    '',
    '### Karar Rehberi',
    '',
    '```',
    'Ofis ortami, 10G, standart ekipman → Cat6A',
    'Endustriyel, yuksek EMI, ozel konnektor → Cat7',
    'Veri merkezi, kisa mesafe (30m), 25/40G → Cat8',
    '```',
    '',
    '---',
    '',
    '## TIA-568 Kurulum Standartları',
    '',
    '- Yatay kablo: Cat6A minimum',
    '- Maksimum yatay mesafe: 90m kablo + 10m patch = 100m',
    '- Çalışma alanı çıkışı: Minimum 2 port',
    '',
    '```',
    'Minimum bukme yaricapi:',
    '  Cat6A UTP: Kablo capinin 4 kati',
    '  Cat6A S/FTP: Kablo capinin 8 kati',
    '',
    'Maksimum cekme kuvveti:',
    '  4 ciftli Cat6A: 110 N (25 lbf)',
    '',
    'Guc kablosuyla minimum mesafe: 150mm',
    '```',
    '',
    '---',
    '',
    '## Fluke Networks ile Sertifikasyon Testi',
    '',
    '### Cat6A Test Kriterleri (TIA-568-C.2)',
    '',
    '```',
    'Wire Map: Tum 8 telin dogru sonlanmasi',
    'Length: <=100m',
    'Insertion Loss (IL): <=20.9 dB @ 500 MHz',
    'Return Loss (RL): >=10.0 dB @ 500 MHz',
    'NEXT: >=35.5 dB @ 500 MHz',
    'Propagation Delay: <=555 ns',
    'Delay Skew: <=45 ns',
    '```',
    '',
    '### Yaygın Test Hataları',
    '',
    '| Hata | Olası Neden | Çözüm |',
    '|------|-------------|-------|',
    '| NEXT fail | Hatalı sonlandırma (>13mm untwist) | Yeniden sonlandır |',
    '| Wire map open | Kırık tel veya gevşek konnektör | Konnektörü değiştir |',
    '| Length exceed | 100m üzeri kablo | Yeniden yönlendir |',
    '| Return Loss fail | Aşırı bükülmüş kablo | Hasar noktasını bul |',
    '',
    '---',
    '',
    '## Fiber Optik Kablolama',
    '',
    '| Tip | Çekirdek | Maks. Mesafe | Kullanım |',
    '|-----|----------|--------------|---------|',
    '| OS2 (Single-mode) | 9 µm | 10+ km | WAN, bina arası |',
    '| OM3 (Multi-mode) | 50 µm | 300m/10G | Veri merkezi |',
    '| OM4 (Multi-mode) | 50 µm | 550m/10G | Veri merkezi |',
    '| OM5 (WBMMF) | 50 µm | 150m/100G | Veri merkezi |',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'Kurumsal yapısal kablolama projesinde: standart ofis ortamları için **Cat6A**, endüstriyel ve yüksek EMI ortamlar için **Cat7**, veri merkezi kısa mesafeleri için **Cat8** tercih edin. **Yitser Teknoloji** olarak ANSI/TIA-568 standardında, Fluke Networks sertifikalı test raporlarıyla teslim garantisi verdiğimiz yapısal kablolama hizmetleri sunuyoruz.',
  ].join('\n')
}

function getWS2025(): string {
  return [
    '## Windows Server 2025 Nedir?',
    '',
    'Windows Server 2025, Microsoft\'un Ekim 2024\'te genel kullanıma sunduğu en güncel sunucu işletim sistemidir. Long-Term Servicing Channel (LTSC) olarak yayınlanan bu sürüm **2034 yılına kadar** genişletilmiş destek kapsamındadır.',
    '',
    '- Ana akım destek: 9 Ekim 2029',
    '- Genişletilmiş destek: 10 Ekim 2034',
    '',
    '---',
    '',
    '## Öne Çıkan Yenilikler',
    '',
    '### 1. Hotpatch Desteği (Azure Arc ile)',
    '',
    'Yeniden başlatma gerektirmeyen güvenlik yamaları. Azure Arc ile yönetilen sunucularda:',
    '',
    '- Yıllık ortalama 8 güvenlik yaması yeniden başlatma gerektirmez',
    '- Planlı bakım pencereleri azalır',
    '- Üretim ortamlarında kesinti minimuma iner',
    '',
    '```powershell',
    '# Hotpatch politikası - Azure Policy ile uygulama',
    '$policyDef = Get-AzPolicyDefinition | Where-Object {',
    '    $_.Properties.DisplayName -like "*Hotpatch*Windows Server 2025*"',
    '}',
    '',
    'New-AzPolicyAssignment `',
    '    -Name "Enable-WS2025-Hotpatch" `',
    '    -PolicyDefinition $policyDef `',
    '    -Scope "/subscriptions/your-sub-id/resourceGroups/YITSER-Prod-RG"',
    '```',
    '',
    '---',
    '',
    '### 2. SMB over QUIC',
    '',
    'Geleneksel TCP/445 yerine QUIC protokolü üzerinden SMB paylaşımları.',
    '',
    '```powershell',
    '# SMB QUIC - sertifika ile dinleyici ekle',
    '$cert = Get-ChildItem -Path Cert:\\LocalMachine\\My |',
    '    Where-Object {$_.Subject -like "*fileserver.yitser.com*"}',
    '',
    'New-SmbServerCertificateMapping `',
    '    -Name "FileServer-QUIC" `',
    '    -Thumbprint $cert.Thumbprint `',
    '    -StoreName "My" `',
    '    -Subject "fileserver.yitser.com"',
    '```',
    '',
    '---',
    '',
    '### 3. SMB Sıkıştırma',
    '',
    '```powershell',
    '# Sunucu tarafı sıkıştırma',
    'Set-SmbServerConfiguration -EnableSMBCompression $true',
    '',
    '# Sıkıştırma istatistikleri',
    'Get-SmbConnection | Select-Object ComputerName, Dialect, *Compress*',
    '```',
    '',
    '---',
    '',
    '### 4. Active Directory Yenilikleri',
    '',
    '**Delegated Managed Service Account (dMSA):**',
    '',
    '```powershell',
    '# dMSA oluşturma',
    'New-ADServiceAccount `',
    '    -Name "svc-webapp-prod" `',
    '    -DNSHostName "webapp-prod.yitser.local" `',
    '    -PrincipalsAllowedToRetrieveManagedPassword "WEB-SERVERS" `',
    '    -KerberosEncryptionType AES256',
    '',
    '# dMSA doğrulama',
    'Test-ADServiceAccount -Identity "svc-webapp-prod"',
    '```',
    '',
    '---',
    '',
    '## Standard vs Datacenter',
    '',
    '| Özellik | Standard | Datacenter |',
    '|---------|----------|------------|',
    '| Sanal makine hakları | 2 VM | Sınırsız VM |',
    '| Storage Spaces Direct | Hayır | Evet |',
    '| Software Defined Networking | Hayır | Evet |',
    '| Fiyat | Normal | ~2x |',
    '',
    '---',
    '',
    '## Windows Server 2022\'den 2025\'e Geçiş',
    '',
    '```powershell',
    '# In-place upgrade - setup.exe ile',
    'Mount-DiskImage -ImagePath "D:\\WS2025.iso"',
    'Start-Process "$($driveLetter):\\setup.exe" -ArgumentList "/auto upgrade /quiet /noreboot"',
    '```',
    '',
    '**Geçiş önerileri:**',
    '- Önce test ortamında uygula (minimum 2 hafta)',
    '- Snapshot/backup al — geri dönüş planı şart',
    '- Uygulama uyumluluğunu kontrol et',
    '- Domain functional level\'ı güncelle',
    '',
    '```powershell',
    '# Domain Functional Level yükselt',
    'Set-ADDomainMode -Identity "yitser.local" -DomainMode Windows2025Domain',
    'Set-ADForestMode -Identity "yitser.local" -ForestMode Windows2025Forest',
    '```',
    '',
    '---',
    '',
    '## Sonuç',
    '',
    'Windows Server 2025, özellikle hotpatch desteği ve gelişmiş Active Directory özellikleriyle kurumsal altyapı için değerli bir güncelleme sunmaktadır. **Yitser Teknoloji** olarak WS2025 değerlendirmesi, lisanslama optimizasyonu ve geçiş projelendirmesi konularında kapsamlı hizmet sunuyoruz.',
  ].join('\n')
}
